import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Quickstart',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Understanding FST',
      items: [{type: 'autogenerated', dirName: 'understanding'}],
    },
    {
      type: 'category',
      label: 'FST In Action',
      items: [{type: 'autogenerated', dirName: 'fst-in-action'}],
    },
    {
      type: 'category',
      label: 'Features',
      items: [{type: 'autogenerated', dirName: 'features'}],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: [{type: 'autogenerated', dirName: 'workflows'}],
    },
    {
      type: 'category',
      label: 'Component Developers',
      items: [{type: 'autogenerated', dirName: 'developers'}],
    },
    {
      type: 'category',
      label: 'Process Pack API',
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
  ],
};

export default sidebars;
